# Generated by Django 4.1.4 on 2022-12-13 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postsApp', '0003_alter_post_comment_count_alter_post_like_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_content', to='postsApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweet_user_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retweetsApp_retweet',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
