# Generated by Django 4.1.4 on 2022-12-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0002_post_is_comment_post_response_to_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='retweet_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
