# Generated by Django 4.1.4 on 2022-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0003_alter_post_comment_count_alter_post_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_pseudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
