# Generated by Django 4.1.4 on 2022-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="name", new_name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
    ]
