# Generated by Django 4.1.4 on 2022-12-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usersApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="about",),
        migrations.RemoveField(model_name="user", name="followers_count",),
        migrations.RemoveField(model_name="user", name="following_count",),
    ]
